@startuml

User -- (Bottom Tab)
(Bottom Tab) -- (Home)
note right of (Home) : Jars.js

(Home) --> (Transaction) : add from selected jar
note right of (Transaction) : AddTransaction.js

(Home) --> (New Jar): create jar
note right of (New Jar) : JarEdit.js

(Home) --> (Jar Details)
note right of (Jar Details) : Jar.js

(Jar Details) --> (Jar Edit) : edit jar
note right of (Jar Edit) : JarEdit.js

(Bottom Tab) -left- (Add)
note right of (Add) : AddTransaction.js
(Add) --> (Home) : returns back to Home

(Bottom Tab) -- (Settings)
note right of (Settings) : Settings.js


@enduml
