@startuml

title: Badge Colors in Jars.js

start
partition avalible {
  if (isBudget)
    :burn + goal.amount;
  else
    :amount + goal.amount;
  endif
}

if (!isBudget)
#e8e8e8:Black;
else

if (avalible < -5)
#f71a1a:Red;
else if (avalible < 5)
#e8e8e8:Black;
else if (item.amount < 0)
#ffac1d:Orange;
else
#7ef421:Green;
endif

endif
end
@enduml
