@startuml

object catagories
object catagory {
  id: string
  name: string
}

object jars
object jar {
  id: string
  name: string
  catId: catagory.id
  desc: string
  amount: number
  goal: object
}
object jar.goal {
  min: number
  max: number
  repeat: string\n[month, year, not]
}

object root {
  lastUpdate: date
  tobeBudgetted: number
}

object transactions
object transaction {
  id: string
  amount: number
  date: date
  jar: object(
    id: string
    name: string
  )
}


catagories --* "*" catagory
jars --* "*" jar
transactions --* "*" transaction

jar -left- catagory
transaction "static" -left- jar
jar "goal" <|-- jar.goal

@enduml
