@startuml

object catagories
object catagory {
  id: string
  name: string
}

object envelopes
object envelope {
  id: string
  name: string
  catId: catagory.id
  desc: string
  amount: number
  ?goals: array<goal>
}
object envelope.goal {
  minAmount: number
  maxAmount: number
}

object accounts
object account {
  id: string
  name: string
  type: array
  amount: number
}
object account.type {
  0: To be budgetted
  1: Bank
  2: People
  3: Company
}

object transactions
object transaction {
  id: string
  amount: number
  envelope: envelope.id
  account: account.id
  payee: account.id
  date: date
  ?repeat: object
  ?type: type.id
}


catagories --* "*" catagory
envelopes --* "*" envelope
accounts --* "*" account
transactions --* "*" transaction

envelope -- catagory
transaction -- envelope
transaction -- account
account <|-- account.type
envelope "*" <|-- envelope.goal

@enduml
